### ISSUE TITLE
amcl 3d使用思路请教

### ISSUE THREAD

**Issue by ZLIANG-code** [chengwei0427/amcl3d_test#1]
您好，我最近在做视觉slam导航的工作，偶然间发现您使用amcl3d进行定位工作，我想请教您这个包的使用思路。如果能够得到您的回复与帮助，我将非常感谢

**Comment by chengwei0427** [comment]
你好，感谢关注；
这个是一个简单的基于amcl的3D激光定位，思路也很简单，因为时间比较久了，建议你先看下代码，后续如果有问题，可以交流一下；

**Comment by ZLIANG-code** [comment]
感谢您的回复。
在我的工作中，根据视觉SLAM利用稠密点云地图建立了三维的八叉树地图，然后再将八叉树地图转换为二维的栅格地图，最后利用amcl进行定位以及导航。我偶然间在ros官网看到了amcl 3d的介绍，因此也搜到了您的博客和代码。我想请教能否直接在我生成的三维八叉树地图里利用amcl3d包进行定位，在三维的八叉树地图中是否也有相应的导航方法。
我是一个研一新生，刚接触这方面不太懂，望您海涵，期待您的回复。


|
| 赵亮
太原理工大学
|
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年11月21日 13:10 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [chengwei0427/amcl3d_test] amcl 3d使用思路请教 (Issue #1) |

你好，感谢关注；
这个是一个简单的基于amcl的3D激光定位，思路也很简单，因为时间比较久了，建议你先看下代码，后续如果有问题，可以交流一下；

**Comment by chengwei0427** [comment]
你好，理论上来说，是可以用三维八叉树进行定位的，可能需要你去做相应的适配才行（主要是权重计算部分）；关于导航，3D导航也有的，关注一下无人机导航相关即可。

**Comment by ZLIANG-code** [comment]
好的，感谢


|
| 赵亮
太原理工大学
|
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年11月21日 13:28 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [chengwei0427/amcl3d_test] amcl 3d使用思路请教 (Issue #1) |

你好，理论上来说，是可以用三维八叉树进行定位的，可能需要你去做相应的适配才行（主要是权重计算部分）；关于导航，3D导航也有的，关注一下无人机导航相关即可。
